<?php

// This is auto-generated file. Do NOT modify.
// Cache Time: 2016-07-07 19:04:42

$settings = array(
	'allow_access' => '1',
	'allow_reg' => '0',
	'antiads_keyword' => 'adsbygoogle',
	'api_key' => '3bcd2df746dd1d7d18b6e46472d48d96',
	'connect_uc_type' => 'discuz',
	'contact_code' => 'aHR0cDovL3dwYS5xcS5jb20vbXNncmQ/dj0zJnVpbj0yMzMxMjM0NDAxJnNpdGU9cXEmbWVudT15ZXM=',
	'contact_us' => 'xqzyw@qq.com',
	'cookie_domain' => '',
	'credit_convert' => '1',
	'debug_info' => '1',
	'default_amount' => '10',
	'deny_extension' => 'vbs,php,asp,aspx,jsp,pl,sh,htm,html,js,shtml',
	'encrypt_key' => 'd14b70e40fb0b74ebf49d03a5ad293d1',
	'file_dl_expires' => '3600',
	'filter_extension' => 'asp,asa,aspx,ascx,dtd,xsd,xsl,xslt,as,wml,java,vtm,vtml,jst,asr,php,php3,php4,php5,vb,vbs,jsf,jsp,pl,cgi,js,html,htm,xhtml,xml,css,shtm,cfm,cfml,shtml,bat,sh',
	'forget_verycode' => '0',
	'ftp_api_url' => 'http://216.227.135.154/',
	'ftp_ip' => 'ftp://216.227.135.154/',
	'ftp_root' => '/www/web/upload_cloud/public_html/ftproot/',
	'gzipcompress' => '1',
	'how_downs_credit' => '1000',
	'invite_register_encode' => '0',
	'login_info' => 'asd',
	'login_verycode' => '1',
	'max_file_size' => '0',
	'max_size' => '100 M',
	'meta_description' => '甲骨盘',
	'meta_ext' => 'PG1ldGEgY29udGVudD0nYmxvZ2dlcicgbmFtZT0nZ2VuZXJhdG9yJy8+',
	'meta_keywords' => '网盘,甲骨盘,网赚网盘',
	'miibeian' => '粤ICP备xxx号',
	'min_to_income' => '20',
	'online_demo' => '0',
	'open_index_fast_upload_box' => '1',
	'open_index_file_list' => '1',
	'open_index_site_desc' => '1',
	'open_report' => '1',
	'open_rewrite' => '0',
	'open_seo' => '1',
	'open_verycode' => '1',
	'perpage' => '20',
	'powered_info' => '1',
	'register_verycode' => '1',
	'reg_info' => 'asd',
	'report_word' => 'bat,sh',
	'secs_loading' => '6',
	'secure_login' => '1',
	'site_notify' => 'PGEgaHJlZj0iLi8iPue9keebmOmmlumhtTwvYT4gfA0KPGEgaHJlZj0iaHR0cDovL3d3dy5waHBkaXNrLmNvbS9zZXJ2aWNlc196Y29yZS5odG1sIj5QSFBEaXNrIFotQ29yZee9kei1mueJiDwvYT4=',
	'site_stat' => '',
	'site_subtitle' => '从甲骨文开始记录分享您的文件',
	'site_title' => '甲骨盘',
	'smtp_email' => 'cj22@vip.qq.com',
	'smtp_name' => '甲骨盘系统邮件',
	'smtp_passwd' => 'tbpdeyipuxkbbgbb',
	'smtp_port' => '465',
	'smtp_server' => 'smtp.qq.com',
	'suipay_appid' => '9',
	'suipay_appid_reseller' => '10',
	'suipay_key' => '43de63c7eef43c9c5dfcab0a4df31f14',
	'suipay_key_reseller' => 'd3b8f723f395eb3e5edf75b0dc5cf2ae',
	'upload_url' => 'http://216.227.135.154/',
	'user_active' => '1',
	'version_info' => '1',
	'verycode_type' => '2',
	'website_url' => 'http://www.jiagupan.com/',
);

?>
